
import React, { useState, useEffect, useRef } from 'react';
import { useGame } from '../context/GameContext';
import ArrowLeftIcon from './icons/ArrowLeftIcon';
import BookOpenIcon from './icons/BookOpenIcon';
import MusicNoteIcon from './icons/MusicNoteIcon';
import BriefcaseIcon from './icons/BriefcaseIcon';
import FireIcon from './icons/FireIcon';
import ChartBarIcon from './icons/ChartBarIcon';
import StarIcon from './icons/StarIcon';
import AmaAwardIcon from './icons/AmaAwardIcon';

interface GuideSection {
    id: string;
    title: string;
    icon: React.ReactNode;
    content: React.ReactNode;
}

const guideSections: GuideSection[] = [
    {
        id: 'getting-started',
        title: 'Getting Started',
        icon: <BookOpenIcon className="w-5 h-5" />,
        content: (
            <>
                <p>Welcome to Red Mic! Your goal is to become a music superstar. You'll record songs, release projects, build a fanbase, and climb the charts. Success hinges on managing three key stats:</p>
                <ul className="list-disc list-inside space-y-2 pl-2">
                    <li><strong>Money:</strong> Your cash on hand. Used for everything from studio time to promotions. Earn it from streams, views, sales, and gigs.</li>
                    <li><strong>Popularity (0-100):</strong> A long-term measure of your fame. It grows with successful releases and decays slowly if you're inactive. Higher popularity leads to more organic streams, sales, and social media engagement.</li>
                    <li><strong>Hype (0-1000):</strong> A short-term measure of your buzz. Generated by new releases, promotional activities, and gigs. Hype decays every week. High hype provides a massive boost to streams for your entire catalog.</li>
                </ul>
            </>
        )
    },
    {
        id: 'making-a-hit-song',
        title: 'How to Make a Hit Song',
        icon: <StarIcon className="w-5 h-5" />,
        content: (
            <>
                <p>Creating a chart-topping hit involves more than just pressing "Record". Here's the winning formula:</p>
                <h3 className="font-bold text-red-400 mt-4">1. Invest in Studio Quality</h3>
                <p>The most important stat in the game is <strong className="text-white">Song Quality</strong>. If your song quality is below 80, it will be hard to make it a global smash. Always use the most expensive studio you can afford (e.g. Abbey Road) to maximize your chances of generating an 80+ or 90+ quality song.</p>
                
                <h3 className="font-bold text-red-400 mt-4">2. Build Hype Pre-Release</h3>
                <p>Hype acts as a multiplier for streams. Before dropping your single, do gigs, answer PopBase questions favorably, start fan wars on X, and accept feature/magazine offers. You want your Hype to be as high as possible the week the song drops.</p>

                <h3 className="font-bold text-red-400 mt-4">3. Massive Playlist & Payola Push</h3>
                <p>In the "Spotify for Artists" app, ALWAYS pitch your single to Editorial Playlists before launch. Once released, immediately go to the Payola app and dump money into Radio rotation, TikTok influencers, and Spotify playlisting. The more you spend, the higher it climbs.</p>

                <h3 className="font-bold text-red-400 mt-4">4. Drop A Music Video</h3>
                <p>Go to the YouTube app and drop a High Budget Music Video for the song simultaneously. This adds massive first-week streams and pushes the song further up the Billboard Hot 100.</p>
            </>
        )
    },
    {
        id: 'how-to-become-critically-acclaimed',
        title: 'Critical Acclaim & Awards',
        icon: <AmaAwardIcon className="w-5 h-5 text-zinc-300" />,
        content: (
            <>
                <p>To win GRAMMYs, AMAs, Oscars, and end up with a legacy that lasts forever, you need a different strategy than just raw streams.</p>
                <h3 className="font-bold text-red-400 mt-4">1. Quality Over Everything</h3>
                <p>Award shows look heavily at the underlying quality of your music. A 95-quality album with moderate streams will almost always beat a 70-quality album with billions of streams at the GRAMMYs. Delete low-quality songs from your studio so they don't drag down your album's average.</p>
                
                <h3 className="font-bold text-red-400 mt-4">2. Submit on Time</h3>
                <p>Check your Inbox religiously. Submissions for Oscars, VMAs, AMAs, and GRAMMYs come at specific times of the year and have a limited submission window. If you miss the email, you miss the awards year.</p>

                <h3 className="font-bold text-red-400 mt-4">3. Soundtrack Dominance</h3>
                <p>If you get offered to write a track for a movie (e.g. <em>Wicked</em>, <em>Breaking Bad</em>), make an incredibly high-quality song for it. Movie soundtracks are the ONLY way to be nominated for "Best Original Song" at the Oscars.</p>

                <h3 className="font-bold text-red-400 mt-4">4. Perform at the Shows</h3>
                <p>If you are nominated, the award show committee will often reach out to ask you to perform on their stage. Doing so boosts your favor with the voting body and significantly raises your popularity.</p>
            </>
        )
    },
    {
        id: 'music-lifecycle',
        title: 'The Music Lifecycle',
        icon: <MusicNoteIcon className="w-5 h-5" />,
        content: (
            <>
                <h3 className="font-bold text-red-400">1. Recording Songs</h3>
                <p>Use the 'Studio' app to record. The quality of your song (0-100) is the most critical factor for its success. The studio you choose determines the possible quality range.</p>
                
                <h3 className="font-bold text-red-400 mt-4">2. Releasing Music</h3>
                <p>Go to the 'Release Hub' to package unreleased songs. You can release a <strong>Single</strong> (1 song), an <strong>EP</strong> (3-7 songs), or an <strong>Album</strong> (8+ songs). Releasing independently gives you full control, but signing to a label offers promotional power.</p>

                <h3 className="font-bold text-red-400 mt-4">3. Promotion</h3>
                <p>Use the 'Payola' app to run promotional campaigns. This costs money weekly but multiplies your streams/views. You can also pitch songs to Spotify playlists via the 'Spotify for Artists' app for a potential boost.</p>

                <h3 className="font-bold text-red-400 mt-4">4. Music Videos</h3>
                <p>Create videos in the 'YouTube' app. A Music Video gives the biggest view boost, followed by Live Performances and Interviews.</p>
            </>
        )
    },
    {
        id: 'career-progression',
        title: 'Career Progression',
        icon: <BriefcaseIcon className="w-5 h-5" />,
        content: (
            <>
                <h3 className="font-bold text-red-400">Gigs & Tours</h3>
                <p>Perform live shows in the 'Gigs' app to earn quick cash and hype. As your popularity grows, you'll unlock bigger venues. In the 'Ticketmaster' app, you can plan multi-city tours, which are a massive source of income.</p>
                
                <h3 className="font-bold text-red-400 mt-4">Record Labels</h3>
                <p>Use the 'Labels' app to seek a record deal. You'll need to meet their stream requirements. Once signed, you submit music for approval. They handle releases and provide a huge promotional multiplier.</p>
                <p>Beware of <strong>"Petty Labels"</strong> (e.g., Quality Control, TDE). If you leave their contract, they will take down all music you released with them. You can later re-record these songs to reclaim your masters.</p>

                <h3 className="font-bold text-red-400 mt-4">Business Ventures</h3>
                <p>Hire staff in the 'Management' and 'Security' apps. Managers automatically book gigs and unlock higher-tier opportunities. Security teams reduce the chance of your unreleased music leaking.</p>
            </>
        )
    },
    {
        id: 'fame-and-image',
        title: 'Fame & Public Image',
        icon: <FireIcon className="w-5 h-5" />,
        content: (
            <>
                <h3 className="font-bold text-red-400">Social Media (X)</h3>
                <p>Use the 'X' app to engage with your fanbase. You can make normal posts, start "fan wars" against rival artists for a hype boost, or "push" a song on iTunes during a fan war. The media (PopBase, TMZ) will also post about your activities, creating buzz and sometimes controversy.</p>

                <h3 className="font-bold text-red-400 mt-4">Stage Name Changes</h3>
                <p>As an independent artist, you are allowed to reinvent yourself by changing your stage name up to two times via the 'Profile' tab in Spotify for Artists.</p>
                <p>However, when dealing with record labels, they may have an opinion on your brand: <br/>Micro, Small, and "Petty" labels have a 50% chance of demanding a name change when you try to sign. Petty labels will force you into picking from random names, while smaller labels will allow you to pick your own, or force you to pay a costly "Name Change Settlement Fee" if you want to keep your current name.</p>

                <h3 className="font-bold text-red-400 mt-4">Media Features</h3>
                <p>As you gain traction, you'll receive offers in your 'Inbox' for interviews and performances with platforms like Genius, The Tonight Show, and Vogue. Accepting these provides significant hype and popularity boosts.</p>

                <h3 className="font-bold text-red-400 mt-4">Exclusive Content (OnlyFans)</h3>
                <p>Once you've built a dedicated fanbase, you can create an OnlyFans profile to monetize exclusive content and interact more directly with your top supporters, creating a new revenue stream.</p>
            </>
        )
    },
    {
        id: 'charts-and-awards',
        title: 'Charts & Awards',
        icon: <ChartBarIcon className="w-5 h-5" />,
        content: (
            <>
                <h3 className="font-bold text-red-400">How Charts Work</h3>
                <p>Song charts (like the Billboard Hot 100) are based purely on weekly streams. Album charts use "album equivalent units," which combine streams from album tracks with pure sales from your merch store (vinyls, CDs).</p>
                <p><strong>Recurrent Rule:</strong> A song is removed from the Hot 100 if it has been on the chart for 20+ weeks AND falls below position #50.</p>
                
                <h3 className="font-bold text-red-400 mt-4">Awards Season</h3>
                <p>Each year, you'll get emails to submit your music for the GRAMMYs and your videos for the VMAs. Navigate to the submission pages via your inbox. Winning awards gives a permanent boost to your legacy and popularity.</p>
            </>
        )
    },
    {
        id: 'timeline-and-eras',
        title: 'Timeline & Eras',
        icon: <BookOpenIcon className="w-5 h-5" />,   
        content: (
            <>
                <p>The music industry evolves rapidly as years progress in the game. Here is a definitive guide on how the landscape changes:</p>
                
                <h3 className="font-bold text-red-400 mt-4">Pre-2003: The Physical Golden Age</h3>
                <p><strong>Physical Sales (90% market share):</strong> CDs, Cassettes, and Vinyl rule the world. <strong>Radio (100% impact):</strong> Radio play is the primary way your songs chart. You must dominate radio to succeed. No streaming or digital downloads exist.</p>

                <h3 className="font-bold text-red-400 mt-4">2003 - 2007: The Digital Revolution Begins</h3>
                <p><strong>iTunes & MySpace:</strong> In 2003, digital downloads (iTunes) become active, opening up the digital sales market. Additionally, MySpace becomes available from 2003-2011, allowing you to connect directly with fans, post blogs, and update your profile song for huge hype.</p>
                <p><strong>YouTube (2005):</strong> The ability to post Music Videos, Interviews, and Live Performances debuts. A very critical visual era begins.</p>
                
                <h3 className="font-bold text-red-400 mt-4">2008 - 2011: The Streaming Dawn</h3>
                <p><strong>Spotify & Twitter (X):</strong> In 2008, streaming (Spotify) goes live, slowly eating into market share. 'X' (Twitter) also goes mainstream, shifting organic hype towards micro-blogging and viral fan wars.</p>
                <p><strong>Market Dynamics:</strong> Physical sales steadily decline (dropping to 60%). Digital downloads peak in relevance alongside radio.</p>

                <h3 className="font-bold text-red-400 mt-4">2012 - 2017: The Social Media Boom</h3>
                <p><strong>Instagram (2012):</strong> Visual dominance shifts to Instagram. MySpace dies and is no longer available.</p>
                <p><strong>OnlyFans (2016):</strong> A new way to monetize hardcore fans. Streaming slowly becomes the dominant force over digital and physical sales.</p>
                
                <h3 className="font-bold text-red-400 mt-4">2018+: The Streaming & Short-Form Era</h3>
                <p><strong>TikTok (2018):</strong> Viral short-form video takes over. Songs explode seemingly overnight through trends.</p>
                <p><strong>Market Dynamics:</strong> Streaming has an 85% market share. Pure digital downloads are mostly dead. Physical sales only exist as niche record sales (5% - vinyl resurgence). Radio impact is significantly diluted to 30% of its former glory.</p>
            </>
        )
    },
    {
        id: 'red-mic-pro',
        title: 'Red Mic Pro',
        icon: <StarIcon className="w-5 h-5" />,
        content: (
            <>
                <p>Red Mic Pro is the premium version of the game, designed for players who want more control.</p>
                <ul className="list-disc list-inside space-y-2 pl-2">
                    <li><strong>Edit Stats:</strong> Directly change your money, hype, and popularity.</li>
                    <li><strong>Song Quality:</strong> See the exact quality score of your unreleased songs and edit it.</li>
                    <li><strong>Sign Instantly:</strong> Sign with any label instantly, ignoring their requirements.</li>
                    <li><strong>Gold Theme:</strong> Unlock an exclusive cosmetic gold theme for the UI.</li>
                </ul>
            </>
        )
    },
];

const GameGuideView: React.FC = () => {
    const { dispatch } = useGame();
    const [activeSection, setActiveSection] = useState(guideSections[0].id);
    const sectionRefs = useRef<Record<string, HTMLDivElement | null>>({});
    const contentRef = useRef<HTMLDivElement | null>(null);

    useEffect(() => {
        const observer = new IntersectionObserver(
            (entries) => {
                entries.forEach(entry => {
                    if (entry.isIntersecting) {
                        setActiveSection(entry.target.id);
                    }
                });
            },
            { root: contentRef.current, threshold: 0.3, rootMargin: '-40% 0px -60% 0px' }
        );

        Object.values(sectionRefs.current).forEach(ref => {
            if (ref) observer.observe(ref);
        });

        return () => {
            Object.values(sectionRefs.current).forEach(ref => {
                if (ref) observer.unobserve(ref);
            });
        };
    }, []);

    const scrollToSection = (id: string) => {
        sectionRefs.current[id]?.scrollIntoView({
            behavior: 'smooth',
            block: 'start',
        });
    };

    return (
        <div className="h-screen w-full bg-zinc-900 flex flex-col text-white">
            <header className="p-4 flex items-center gap-4 flex-shrink-0 bg-zinc-900/80 backdrop-blur-sm z-10 border-b border-zinc-700/50">
                <button onClick={() => dispatch({ type: 'CHANGE_VIEW', payload: 'game' })} className="p-2 rounded-full hover:bg-white/10">
                    <ArrowLeftIcon className="w-6 h-6" />
                </button>
                <h1 className="text-2xl font-bold">Game Guide</h1>
            </header>
            <div className="flex flex-grow overflow-hidden">
                <aside className="w-1/3 md:w-1/4 h-full overflow-y-auto border-r border-zinc-700/50 p-4">
                    <nav className="space-y-1">
                        {guideSections.map(section => (
                            <button
                                key={section.id}
                                onClick={() => scrollToSection(section.id)}
                                className={`w-full flex items-center gap-3 p-2 rounded-md text-left transition-colors text-sm font-semibold ${
                                    activeSection === section.id
                                        ? 'bg-red-500/20 text-red-400'
                                        : 'text-zinc-300 hover:bg-zinc-800'
                                }`}
                            >
                                <span className="flex-shrink-0">{section.icon}</span>
                                <span className="truncate">{section.title}</span>
                            </button>
                        ))}
                    </nav>
                </aside>
                <main ref={contentRef} className="w-2/3 md:w-3/4 h-full overflow-y-auto p-4 md:p-6">
                    <div className="space-y-8 max-w-2xl mx-auto">
                        {guideSections.map(section => (
                            <div
                                key={section.id}
                                id={section.id}
                                ref={el => sectionRefs.current[section.id] = el}
                                className="bg-zinc-800 p-4 rounded-lg scroll-mt-4"
                            >
                                <h2 className="text-2xl font-bold text-red-400 mb-4">{section.title}</h2>
                                <div className="space-y-3 text-zinc-300 leading-relaxed">
                                    {section.content}
                                </div>
                            </div>
                        ))}
                         <div className="h-32"></div>
                    </div>
                </main>
            </div>
        </div>
    );
};

export default GameGuideView;
